---
title: "Final_Project"
author: Hailey Armor, Lucy Karn, and Justin Kruljac
date: 4/29/2025
date-format: long
format: pdf
---

## Overview

The goal of this repo is to provide the readers with a statistical insight of the data provided from the National Center of Health Statistics (NCHS). We also would like to compare this data to the number of COVID cases in NYC in the same years. From these two data sets we will calculate a difference in proportions and determine if it is statistically significant.

## Provenance

One data set is from the National Center of Health Statistics, it contains data ranging from 2019-2023 regarding the the frequency of missed work due to illness, injury, or disability over the given time period. The other data set is from NYC Dept. of Health COVID Report and it contains cases of COVID starting in 2020 and records them daily. Each case in this data set is a day, where as each case in the first data set is a year. 

We would like to point out a possible association between an increase the number of work days missed and the post-COVID era. The purpose of this doc is to create a correlation table and data visualization for these two data sets to see and prove that there is a correlation between sick days and COVID cases. 

## Fair and Care Principles

Our main data set of number of people under 18 taking a sick day from school adheres to the FAIR principles because it is accessible, findable, and reusable. This data set is available to the public and uses language that is easily understood. It can also be reused to observe smaller groups such as race, location, age, and health insurance.

Our second data set of COVID cases adheres more to the CARE principles. It focuses more on data collected for collective benefit and for the government to use to track COVID. While this data set doesn't exactly capture or reflect directly on other cultures and worldviews, it can be used to draw conclusions about COVID that relate to how COVID is moving worldwide. This data set was collected ethically and is going to be for future use.

## Data Visualizations

## Conclusion

## Data Sources and Acknowledgements

## Authors

Hailey Armor hpa52552\@psu.edu 
Lucy Karn lek5494\@psu.edu 
Justin Kruljac jck5770\@psu.edu
